version: "3"
services:

  mysql:
    container_name: nodeDB
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 4112
      MYSQL_DATABASE: node_js
      MYSQL_USER: luke
      MYSQL_PASSWORD: 4112
    ports:
      - '4306:3306'
    volumes:
      - ./mysql:/var/lib/mysql