version: '3.8'

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=4112
      - MYSQL_DATABASE=node_js
    ports:
      - '8080:8080'
    volumes:
      - db:/var/lib/mysql
  app:
    depends_on:
      - mysqldb
    build: ./app
    restart: unless-stopped
    ports:
      - '6868:6868'
    environment:
      - DB_HOST=localhost
      - DB_USER=luke
      - DB_PASSWORD=4112
      - DB_NAME=luke
      - DB_PORT=3306
    stdin_open: true
    tty: true

volumes:
  db: