version: "3"
services:
  node:
    build: ./
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 4112
      MYSQL_DATABASE: node_js
      MYSQL_USER: luke
      MYSQL_PASSWORD: 4112

volumes:
  db-data: {}