swagger: '2.0'
info:
  title: Bookstore API
  version: 1.0.0
  description: A simple API to manage a bookstore
basePath: /api
schemes:
  - http
paths:
  /books:
    get:
      summary: Get all books
      responses:
        '200':
          description: A list of books
          schema:
            type: array
            items:
              $ref: 'src/entity/Book'
    post:
      summary: Add a book
      parameters:
        - in: body
          name: book
          schema:
            $ref: '#/definitions/Book'
      responses:
        '200':
          description: The added book
          schema:
            $ref: '#/definitions/Book'
  /books/{name}:
    get:
      summary: Get a book by name
      parameters:
        - in: path
          name: name
          type: string
          required: true
      responses:
        '200':
          description: The book with the given name
          schema:
            $ref: '#/definitions/Book'
    put:
      summary: Update a book by name
      parameters:
        - in: path
          name: name
          type: string
          required: true
        - in: body
          name: book
          schema:
            $ref: '#/definitions/Book'
      responses:
        '200':
          description: The updated book
          schema:
            $ref: '#/definitions/Book'
    delete:
      summary: Delete a book by name
      parameters:
        - in: path
          name: name
          type: string
          required: true
      responses:
        '200':
          description: The deleted book
          schema:
            $ref: '#/entity/Book'
definitions:
  Book:
    type: object
    required:
      - name
      - author
    properties:
      id:
        type: integer
      name:
        type: string
      author:
        type: string
